version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-nginx
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
      - ./docker/config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mongodb
      - php
    networks:
      - app-network
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-php
    ports:
        - ":9000"
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DATABASE: renzora
      MONGO_USERNAME: admin
      MONGO_PASSWORD: password
      JWT_KEY: key
    volumes:
      - ./web:/var/www/html
    networks:
      - app-network
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
      - ./docker/db:/docker-entrypoint-initdb.d
    networks:
      - app-network
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
networks:
  app-network:
    driver: bridge
volumes:
  db-data:
