version: '3'

services:
  web:
    build:
      context: ./app/web
      dockerfile: ../../docker/Dockerfile-app
    ports:
      - "80:80"
    volumes:
      - ./app/web:/var/www/html
    depends_on:
      - server
      - db

  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-server
    volumes:
      - ./server:/app/server
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
