version: '3'
services:
  webserver:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-apache
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
      - ./docker/config/apache.conf:/etc/apache2/sites-enabled/000-default.conf
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DATABASE: renzora
      MONGO_USERNAME: admin
      MONGO_PASSWORD: password
      JWT_KEY: key
    depends_on:
      - mongodb
    networks:
      - app-network
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
      - ./docker/db:/docker-entrypoint-initdb.d
    networks:
      - app-network
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  db-data:
