version: '3'
services:
  # Apache with PHP
  webserver:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-apache
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
      - ./docker/config/apache.conf:/etc/apache2/sites-enabled/000-default.conf
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: password
      DB_DATABASE: renzora
      JWT_KEY: key
    depends_on:
      - db
    networks:
      - app-network

  # MySQL
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: renzora
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  # Node.js server
  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
