# Use the official Node.js image
FROM node:latest

# Install git
RUN apt-get update && apt-get install -y git

# Clone server repository
RUN mkdir -p /root/.ssh && \
    chmod 0700 /root/.ssh && \
    ssh-keyscan github.com >> /root/.ssh/known_hosts

RUN --mount=type=secret,id=ssh_key \
    cp /run/secrets/ssh_key /root/.ssh/id_rsa && \
    chmod 600 /root/.ssh/id_rsa

RUN git clone git@github.com:renzora/server /tmp/server

# Set working directory
WORKDIR /app/server

# Copy package.json and package-lock.json
COPY /docker/package*.json ./

# Install dependencies
RUN npm install

# Copy server files
RUN cp -a /tmp/server/. .

# Expose port (if necessary)
# EXPOSE <port>

# Clean up
RUN rm -rf /tmp/server

# Start the server
CMD ["node", "app.js"]
