FROM php:apache

# Install PDO MySQL extension
RUN docker-php-ext-install pdo pdo_mysql

# Enable mod_rewrite
RUN a2enmod rewrite

# Set ServerName to localhost to suppress warning messages
RUN echo 'ServerName localhost' >> /etc/apache2/apache2.conf